version: "3.8"
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/travel
      - JWT_SECRET=supersecret
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    command: node src/server.js

  # tests:
  #   build: .
  #   environment:
  #     - MONGO_URI=mongodb://mongo:27017/travel
  #     - JWT_SECRET=supersecret
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     - mongo
  #     - redis
  #   command: npm test
